In [1]:
import numpy as np

In [2]:
# 1D Array
#syntax: np.array([values])

In [3]:
a1=np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
a2=np.array([1.1,2.2,3.3,4.5,5.5])
a2

array([1.1, 2.2, 3.3, 4.5, 5.5])

In [5]:
a3=np.array([1,2,3,4,5.5])
a3

array([1. , 2. , 3. , 4. , 5.5])

In [6]:
a4=np.array(['1','2','3.3',"hi"])
a4

array(['1', '2', '3.3', 'hi'], dtype='<U3')

In [7]:
a5=np.array([1,2,3.3],'int')
a5

array([1, 2, 3])

In [8]:
a6=np.array([1,2,3.3],'float')
a6

array([1. , 2. , 3.3])

In [9]:
l1=[1,2,3,4,5]
l1=np.array(l1)
l1

array([1, 2, 3, 4, 5])

In [10]:
# Array operations
#ndim

a1.ndim

1

In [11]:
#size
a1.size

5

In [12]:
a1.dtype

dtype('int32')

In [13]:
a6.dtype

dtype('float64')

In [14]:
# shape
a1.shape

(5,)

In [15]:
a6.shape

(3,)

In [16]:
l1.shape

(5,)

In [17]:
# 2D array
# syntax: np.array([[]])

In [18]:
a7=np.array([[1,2,3,4,5]])
a7

array([[1, 2, 3, 4, 5]])

In [19]:
a7.ndim

2

In [20]:
a8=np.array([[1,2,3,],[4,5,6],[7,8,9]])
a8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a8.ndim

2

In [22]:
a9=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,7,8],[1,5,6.6,7,9]])
a9

array([[1. , 2. , 3. , 4. , 5. ],
       [4. , 5. , 6. , 7. , 8. ],
       [7. , 8. , 9. , 7. , 8. ],
       [1. , 5. , 6.6, 7. , 9. ]])

In [23]:
a9.ndim

2

In [24]:
a9.dtype

dtype('float64')

In [25]:
a9.size

20

In [26]:
a8.size

9

In [27]:
a8.shape

(3, 3)

In [28]:
a9.shape

(4, 5)

In [29]:
# Array Function
# synatx: np.zeros((shape))

In [30]:
a10=np.zeros([3,3],int)
a10

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
a10=np.zeros([5,10],float)
a10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
a11=np.ones([3,3],int)
a11

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
# np.full((3,2),5)

In [34]:
a12=np.full([3,3],5)
a12

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [35]:
# Mathematical Function

In [36]:
import numpy as np

In [37]:
a1= np.array([2,3,4,])
a2=np.array([5,6,1])

In [38]:
np.sum(a1)

9

In [39]:
np.sum(a2)

12

In [40]:
np.sum([a1,a2])

21

In [41]:
np.sum([a1,a2],axis=0)

array([7, 9, 5])

In [42]:
np.sum([a1,a2],axis=1)

array([ 9, 12])

In [43]:
#a1=np.array([2,3,4])
#a2=np.array([5,6,1])
np.subtract(a1,a2)

array([-3, -3,  3])

In [44]:
np.multiply(a1,a2)

array([10, 18,  4])

In [45]:
np.divide(a1,a2)

array([0.4, 0.5, 4. ])

In [46]:
# Additional func
#arange

In [47]:
# np.arange()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# np.arange(start, end+1, step+1)
a1=np.arange(1,11,3)
a1

array([ 1,  4,  7, 10])

In [49]:
# np.arange()
a=np.arange(11)
print(a[::-1])

[10  9  8  7  6  5  4  3  2  1  0]


In [50]:
#Random Number
#syntax: np.random.random((shape))
r2=np.random.random((5,3))
r2

array([[0.10678844, 0.62457369, 0.69236797],
       [0.02969335, 0.72451727, 0.38951596],
       [0.33083452, 0.15550978, 0.82575824],
       [0.82618388, 0.85739752, 0.50458935],
       [0.40428802, 0.28163881, 0.19243152]])

In [51]:
r3=np.random.random((3))
r3

array([0.09244342, 0.02511094, 0.37223292])

In [52]:
r4=np.random.random((3,4))
r4

array([[0.09742098, 0.21527755, 0.99669994, 0.25201665],
       [0.15648871, 0.71787963, 0.26737206, 0.14676653],
       [0.57917945, 0.73190066, 0.90389859, 0.69453716]])

In [53]:
r5=np.random.randint(1,11,(2,2))
r5

array([[10,  3],
       [ 7,  3]])

In [54]:
r6=np.random.randint(1,15,(4))
r6

array([5, 6, 9, 9])

In [55]:
r2=np.identity(3)
r2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
l1=np.identity(3,'int')
l1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
a=np.array([5,6,1,2,9,10,8,7])
a

array([ 5,  6,  1,  2,  9, 10,  8,  7])

In [58]:
a.max()

10

In [59]:
a.min()

1

In [60]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [61]:
np.mean(a)

3.0

In [62]:
np.median(a)

3.0

In [63]:
np.var(a)

2.0

In [64]:
np.std(a)

1.4142135623730951

In [65]:
import pandas as pd

my_list = [1, 2, 3, 4, 5]
s = pd.Series(my_list)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [66]:
a=np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [67]:
a.shape

(3, 3)

In [68]:
a = np.array([-5, -10, -2, -8, -3,])
a = np.abs(a)
print(a)

[ 5 10  2  8  3]


In [69]:
x=np.array([1.5,1.0,9.0,10.5])
s=np.round(x)
s

array([ 2.,  1.,  9., 10.])

In [70]:
import pandas as pd
import numpy as np

In [71]:
l1=np.array([[1,2,3],[4,5,6],[7,8,9]])
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
df=pd.DataFrame(l1.reshape(3,3))
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [73]:
import pandas as pd

In [74]:
l1=[1,2,3,4,5]
l1=pd.Series(l1)
l1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [76]:
import pandas as pd

In [81]:
import numpy as np

In [85]:
s1=np.array([1,2,3,4,])
s1 = pd.Series(s1)
print(s1)

0    1
1    2
2    3
3    4
dtype: int32


In [88]:
d= {'a': 100, 'b': 200, 'c': 300}
d = pd.Series(d)
print(d)

a    100
b    200
c    300
dtype: int64
